-- MySQL Script generated by MySQL Workbench
-- Mon Jul  3 15:18:01 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema flower_shop
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `flower_shop` ;

-- -----------------------------------------------------
-- Schema flower_shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `flower_shop` DEFAULT CHARACTER SET utf8 ;
USE `flower_shop` ;

-- -----------------------------------------------------
-- Table `flower_shop`.`FlowerType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flower_shop`.`FlowerType` ;

CREATE TABLE IF NOT EXISTS `flower_shop`.`FlowerType` (
  `type_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `wilt_days` INT NOT NULL,
  `water_need` VARCHAR(30) NOT NULL,
  `light_need` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`type_id`),
  UNIQUE INDEX `type_id_UNIQUE` (`type_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flower_shop`.`Color`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flower_shop`.`Color` ;

CREATE TABLE IF NOT EXISTS `flower_shop`.`Color` (
  `color_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `color_name` VARCHAR(45) NOT NULL,
  `color_code` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`color_id`),
  UNIQUE INDEX `color_id_UNIQUE` (`color_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flower_shop`.`Flowers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flower_shop`.`Flowers` ;

CREATE TABLE IF NOT EXISTS `flower_shop`.`Flowers` (
  `flower_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `flower_name` VARCHAR(60) NOT NULL,
  `type_id` INT UNSIGNED NOT NULL,
  `color_fl_id` INT UNSIGNED NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `price` DECIMAL(5,2) NOT NULL,
  `quantity` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`flower_id`),
  UNIQUE INDEX `flower_id_UNIQUE` (`flower_id` ASC) VISIBLE,
  INDEX `type_id_idx` (`type_id` ASC) VISIBLE,
  INDEX `color_id_idx` (`color_fl_id` ASC) VISIBLE,
  CONSTRAINT `type_id`
    FOREIGN KEY (`type_id`)
    REFERENCES `flower_shop`.`FlowerType` (`type_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `color_fl_id`
    FOREIGN KEY (`color_fl_id`)
    REFERENCES `flower_shop`.`Color` (`color_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flower_shop`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flower_shop`.`Customer` ;

CREATE TABLE IF NOT EXISTS `flower_shop`.`Customer` (
  `customer_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(15) NOT NULL,
  `lastname` VARCHAR(15) NOT NULL,
  `telephone` VARCHAR(12) NOT NULL,
  `gender` CHAR(3) NOT NULL,
  PRIMARY KEY (`customer_id`),
  UNIQUE INDEX `customer_id_UNIQUE` (`customer_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flower_shop`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flower_shop`.`Employee` ;

CREATE TABLE IF NOT EXISTS `flower_shop`.`Employee` (
  `employee_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(15) NOT NULL,
  `lastname` VARCHAR(15) NOT NULL,
  `work_position` VARCHAR(25) NOT NULL,
  `hiring_date` DATE NOT NULL,
  `salary` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`employee_id`),
  UNIQUE INDEX `employee_id_UNIQUE` (`employee_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flower_shop`.`Payment_method`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flower_shop`.`Payment_method` ;

CREATE TABLE IF NOT EXISTS `flower_shop`.`Payment_method` (
  `payment_method_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Payment_methodcol_name` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`payment_method_id`),
  UNIQUE INDEX `payment_method_id_UNIQUE` (`payment_method_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flower_shop`.`Invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flower_shop`.`Invoice` ;

CREATE TABLE IF NOT EXISTS `flower_shop`.`Invoice` (
  `invoice_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `invoice_number` VARCHAR(60) NOT NULL,
  `customer_id` INT UNSIGNED NOT NULL,
  `employee_id` INT UNSIGNED NOT NULL,
  `date` DATE NOT NULL,
  `total_price` DECIMAL(10,2) NOT NULL,
  `payment_method_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`invoice_id`),
  UNIQUE INDEX `transaction_id_UNIQUE` (`invoice_id` ASC) VISIBLE,
  INDEX `customer_id_idx` (`customer_id` ASC) VISIBLE,
  INDEX `employee_id_idx` (`employee_id` ASC) VISIBLE,
  INDEX `payment_method_id_idx` (`payment_method_id` ASC) VISIBLE,
  CONSTRAINT `customer_inv_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `flower_shop`.`Customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `employee_inv_id`
    FOREIGN KEY (`employee_id`)
    REFERENCES `flower_shop`.`Employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `payment_method_id`
    FOREIGN KEY (`payment_method_id`)
    REFERENCES `flower_shop`.`Payment_method` (`payment_method_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flower_shop`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flower_shop`.`Order` ;

CREATE TABLE IF NOT EXISTS `flower_shop`.`Order` (
  `order_id` INT UNSIGNED NOT NULL,
  `customer_id` INT UNSIGNED NOT NULL,
  `order_date` DATE NOT NULL,
  `invoice_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`order_id`),
  UNIQUE INDEX `order_id_UNIQUE` (`order_id` ASC) VISIBLE,
  INDEX `customer_id_idx` (`customer_id` ASC) VISIBLE,
  INDEX `invoice_id_idx` (`invoice_id` ASC) VISIBLE,
  CONSTRAINT `customer_ord_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `flower_shop`.`Customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `invoice_id`
    FOREIGN KEY (`invoice_id`)
    REFERENCES `flower_shop`.`Invoice` (`invoice_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flower_shop`.`Package_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flower_shop`.`Package_type` ;

CREATE TABLE IF NOT EXISTS `flower_shop`.`Package_type` (
  `package_type_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `package_name` VARCHAR(25) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`package_type_id`),
  UNIQUE INDEX `package_type_id_UNIQUE` (`package_type_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flower_shop`.`Packaging_Material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flower_shop`.`Packaging_Material` ;

CREATE TABLE IF NOT EXISTS `flower_shop`.`Packaging_Material` (
  `material_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `material_name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `price` DECIMAL(5,2) NOT NULL,
  `quantity_in_cm` DECIMAL(6,2) NOT NULL,
  `color_p_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`material_id`),
  UNIQUE INDEX `Material_id_UNIQUE` (`material_id` ASC) VISIBLE,
  INDEX `color_id_idx` (`color_p_id` ASC) VISIBLE,
  CONSTRAINT `color_p_id`
    FOREIGN KEY (`color_p_id`)
    REFERENCES `flower_shop`.`Color` (`color_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flower_shop`.`Packaging_Paper`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flower_shop`.`Packaging_Paper` ;

CREATE TABLE IF NOT EXISTS `flower_shop`.`Packaging_Paper` (
  `package_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `package_type_id` INT UNSIGNED NOT NULL,
  `material_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`package_id`),
  UNIQUE INDEX `package_id_UNIQUE` (`package_id` ASC) VISIBLE,
  INDEX `package_type_id_idx` (`package_type_id` ASC) VISIBLE,
  INDEX `material_id_idx` (`material_id` ASC) VISIBLE,
  CONSTRAINT `package_type_id`
    FOREIGN KEY (`package_type_id`)
    REFERENCES `flower_shop`.`Package_type` (`package_type_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `material_id`
    FOREIGN KEY (`material_id`)
    REFERENCES `flower_shop`.`Packaging_Material` (`material_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flower_shop`.`Order_Details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flower_shop`.`Order_Details` ;

CREATE TABLE IF NOT EXISTS `flower_shop`.`Order_Details` (
  `order_id` INT UNSIGNED NOT NULL,
  `employee_id` INT UNSIGNED NOT NULL,
  `flower_id` INT UNSIGNED NOT NULL,
  `package_id` INT UNSIGNED NOT NULL,
  `quantity` INT UNSIGNED NOT NULL,
  `note` VARCHAR(100) NULL,
  INDEX `order_id_idx` (`order_id` ASC) VISIBLE,
  INDEX `employer_id_idx` (`employee_id` ASC) VISIBLE,
  INDEX `flower_id_idx` (`flower_id` ASC) VISIBLE,
  INDEX `package_id_idx` (`package_id` ASC) VISIBLE,
  CONSTRAINT `order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES `flower_shop`.`Order` (`order_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `employee_ord_id`
    FOREIGN KEY (`employee_id`)
    REFERENCES `flower_shop`.`Employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `flower_id`
    FOREIGN KEY (`flower_id`)
    REFERENCES `flower_shop`.`Flowers` (`flower_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `package_id`
    FOREIGN KEY (`package_id`)
    REFERENCES `flower_shop`.`Packaging_Paper` (`package_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flower_shop`.`Customer_Details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flower_shop`.`Customer_Details` ;

CREATE TABLE IF NOT EXISTS `flower_shop`.`Customer_Details` (
  `customer_id` INT UNSIGNED NOT NULL,
  `mem_since` DATE NOT NULL,
  `adress` VARCHAR(100) NOT NULL,
  `email` VARCHAR(319) NOT NULL,
  `birthday` DATE NOT NULL,
  INDEX `customer_id_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `flower_shop`.`Customer` (`customer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flower_shop`.`Employee_Details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flower_shop`.`Employee_Details` ;

CREATE TABLE IF NOT EXISTS `flower_shop`.`Employee_Details` (
  `employee_id` INT UNSIGNED NOT NULL,
  `adress` VARCHAR(100) NOT NULL,
  `email` VARCHAR(319) NOT NULL,
  `telephone` VARCHAR(12) NOT NULL,
  INDEX `employee_id_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `employee_id`
    FOREIGN KEY (`employee_id`)
    REFERENCES `flower_shop`.`Employee` (`employee_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
